### ISSUE TITLE
Math.log10(1 - Number.EPSILON)

### ISSUE THREAD

**Issue by Yaffle** [rtoy/fdlibm-js#3]
Hi,
`Math.log10(1 - Number.EPSILON)` gives me some strange result on Chrome, 
 What is the right answer?

**Comment by rtoy** [comment]
What do you get and what were you expecting?

I get -1.1102230246251565e-16.  The true answer according to maxima is
-4.821637332766435821255375046554377090472359809221653625773280957b-17

fdlibm-js also gives 1.11022...e-16.  Looks like a bug in Chrome as well as fdlibm-js.

Please file a bug against Chrome (or V8).

**Comment by rtoy** [comment]
You are right about replacing >> with >>>.  But there are more things going on where some intermediate values are off by one bit or so.

**Comment by rtoy** [comment]
I'm mistaken.  I was expecting Number.EPSILON to be the smallest number such that 1+eps is not 1.  It's not.

The true value of log10(1-Number.EPSILON) should be
-9.643274665532872177820028416061321058423420340828882501990975764b-17
With the one-character fix, log10 returns
-9.643274665532871e-17
