### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by NodeGuy** [rtoy/fdlibm-js#6]
What's your license for re-use?

**Comment by rtoy** [comment]
Good question.  Since the original code from Sun had this license:

```
====================================================
Copyright (C) 2004 by Sun Microsystems, Inc. All rights reserved.

Permission to use, copy, modify, and distribute this
software is freely granted, provided that this notice 
is preserved.
====================================================
```

I think using the same license would be best.

If you actually use this for something, I'd appreciate a note saying you're using it for something. Not necessary, but I'd like to know just for fun.

**Comment by rtoy** [comment]
Oh, wait.  There's already a LICENSE file on the master branch.  It's the two-clause BSD license.
